name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 9 # sau 10 dacă folosești pnpm v10 local

      # Setup Node.js (cu cache pnpm)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # Instalează deps
      - run: pnpm install --frozen-lockfile

      # Lint
      - run: pnpm lint

      # Build (rulează doar dacă există script "build" în package.json)
      - run: pnpm build --if-present
