name: CI

on:
  push:
    branches: [ main, chore/**, feat/**, feature/** ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (22.18.0) + pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: pnpm build
