name: CI

on:
  push:
    branches: [ main, chore/**, feat/**, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (22.18.0)
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.15.0
          run_install: false  # instalează pnpm, nu rulează install

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: pnpm build
