name: CI (pnpm + Next)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22          # ok pentru Next 15 și engines din package.json
          cache: 'pnpm'             # cache pe pnpm store (mai rapid)

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10               # pnpm 10.x (evită warning-urile cu 9.x)
          run_install: true         # rulează pnpm install automat, cu lockfile

      - name: Show tool versions
        run: |
          node -v
          pnpm -v

      - name: Run lint
        run: pnpm lint

      - name: Run build
        run: pnpm build

      - name: Upload Next.js build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next/**
            public/**
          retention-days: 5
