
name: CI (pnpm + Next + Vercel)

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  NODE_VERSION: '20'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true
      - run: pnpm lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true
      - run: pnpm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      # pregătește .vercel/ (org/project/token)
      - name: Vercel pull (populate .vercel)
        run: npx -y vercel@latest pull --yes --environment=production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # face build prebuilt (output în .vercel/output)
      - name: Vercel build
        run: npx -y vercel@latest build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # urcă artifactul corect pentru deploy
      - name: Upload prebuilt output
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: .vercel/output

  deploy:
    needs: build
    # pentru PR-uri poți lăsa deploy să nu ruleze
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: .vercel/output
      - name: Deploy to Vercel (prebuilt)
        run: npx -y vercel@latest deploy --prebuilt --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
