deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 1) Populează .vercel/ din proiect (PR = preview)
      - name: Vercel pull (populate .vercel)
        run: npx -y vercel@latest pull --yes --environment=preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # 2) Build local (creează .vercel/output)
      - name: Build (prebuilt)
        run: npx -y vercel@latest build

      # 3) Deploy din .vercel/output (prebuilt)
      - name: Vercel deploy (prebuilt)
        run: npx -y vercel@latest deploy --prebuilt --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
