jobs:
  # ... păstrezi lint / test / build așa cum sunt ...

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./

      - name: Vercel pull (populate .vercel)
        run: npx -y vercel@latest pull --yes --environment=production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Vercel deploy (prebuilt)
        run: npx -y vercel@latest deploy --prebuilt --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
