name: CI (pnpm + Next + Vercel)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js + cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack & pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
          pnpm -v
          node -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Run lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js + cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack & pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js + cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack & pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js
        run: pnpm build

      - name: Upload artifact (.next & public)
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next/**
            public/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
