name: CI (pnpm + Next)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true
  NEXT_TELEMETRY_DISABLED: "1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain (Node + pnpm)
        uses: ./.github/actions/pnpm-setup
        with:
          node-version: 20
          pnpm-version: 9.15.4

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Run lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup toolchain (Node + pnpm)
        uses: ./.github/actions/pnpm-setup
        with:
          node-version: 20
          pnpm-version: 9.15.4
      - name: Install deps
        run: pnpm install --no-frozen-lockfile
      # dacă nu ai teste, poți ține un placeholder sau șterge jobul:
      - name: Run tests
        run: |
          if pnpm -s test --help >/dev/null 2>&1; then pnpm test; else echo "No tests"; fi

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup toolchain (Node + pnpm)
        uses: ./.github/actions/pnpm-setup
        with:
          node-version: 20
          pnpm-version: 9.15.4
      - name: Install deps
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Upload Next.js build artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next/**
            public/**
          retention-days: 5
