name: CI (pnpm + Next + Vercel)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js + cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack & pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
          pnpm -v
          node -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Run lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js + cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack & pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js + cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack & pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js
        run: pnpm build

      - name: Upload artifact (.next & public)
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next/**
            public/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .

      deploy:
    name: Deploy (Vercel prebuilt)
    runs-on: ubuntu-latest
    needs: build
    env:
      NEXT_TELEMETRY_DISABLED: "1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # pnpm & Node – păstrăm același setup ca în celelalte joburi
      - name: Setup pnpm (composite)
        uses: ./.github/actions/setup-pnpm

      # Luăm artifactul produs de jobul build
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: ./

      deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: ./

      - name: Vercel pull (populate .vercel)
        run: |
          pnpm dlx vercel@latest pull --yes --environment=production \
            --token "${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Vercel deploy (prebuilt)
        id: vercel
        run: |
          URL=$(pnpm dlx vercel@latest deploy --prebuilt --prod \
                --token "${{ secrets.VERCEL_TOKEN }}" 2>&1 | tee /dev/stderr | tail -n1)
          echo "url=$URL" >> "$GITHUB_OUTPUT"

      - name: Print deployment URL
        run: echo "Deployed: ${{ steps.vercel.outputs.url }}"
