name: CI (pnpm + Next)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# avoid piling up duplicate runs on the same ref
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  NEXT_TELEMETRY_DISABLED: "1"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'            # cache deps by pnpm-lock.yaml

      # ✅ make pnpm available (fixes “Unable to locate executable file: pnpm”)
      - name: Enable Corepack & activate pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
          pnpm -v
          node -v

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable Corepack & activate pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
          pnpm -v

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # rulează testele dacă adaugi scriptul "test" în package.json; altfel un no-op prietenos
      - name: Run tests (if present)
        run: |
          if pnpm run | grep -qE '^  test'; then
            pnpm test
          else
            echo "No test script, skipping."
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable Corepack & activate pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
          pnpm -v

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js
        run: pnpm build

      - name: Upload Next.js build artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next/**
            public/**
          retention-days: 5
