name: CI (pnpm + Next + Vercel)

on:
  push:
    branches: [ main, chore/magic-v2-groups ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          run_install: true
      - run: pnpm -v
      - run: pnpm lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          run_install: true
      - run: pnpm -v
      - run: pnpm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          run_install: true
      - run: pnpm -v
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: .next
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-build
          path: .next
      - run: npx -y vercel@latest pull --yes --environment=production
      - run: npx -y vercel@latest deploy --prebuilt --prod
