name: CI (pnpm + Next)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true
  NEXT_TELEMETRY_DISABLED: "1"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node 20 + cache pnpm pe baza pnpm-lock.yaml
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # ACTIVĂM pnpm v9 pe această mașină (fiecare job e mașină separată!)
      - name: Enable Corepack and pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
          pnpm -v
          node -v

      # Cache pentru store-ul pnpm (accelerăm instalarea)
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run lint
        run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Enable Corepack and pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Run tests
        run: pnpm test --if-present

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Enable Corepack and pnpm v9
        run: |
          corepack enable
          corepack prepare pnpm@9.15.4 --activate
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build Next.js
        run: pnpm build
      - name: Upload Next.js build artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next/**
            public/**
          retention-days: 5
