name: Nightly E2E

on:
  schedule:
    - cron: '0 2 * * *'   # zilnic 02:00 UTC
  workflow_dispatch: {}   # rulează manual din tab-ul Actions

permissions:
  contents: read

concurrency:
  group: nightly-e2e
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (22.18.0) + pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile

      # Rulează testele doar dacă există scriptul "test:e2e" în package.json
      - name: Run E2E if script exists
        run: |
          if pnpm -s run | grep -q '^test:e2e'; then
            pnpm test:e2e
          else
            echo "No test:e2e script; skipping."
          fi
