name: Release build (zip + attach)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Package build into zip
        run: |
          rm -rf dist && mkdir -p dist
          cp -r .next dist/.next
          [ -d public ] && cp -r public dist/public || true
          cd dist && zip -r ../app-us-build.zip . && cd -
      - name: Create GitHub Release and upload zip
        uses: softprops/action-gh-release@v2
        with:
          files: app-us-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
